---
- name: install libraries for rails
  yum: state=present name={{ item }}
  with_items:
    - gcc-c++
    - glibc-headers
    - patch
    - make
    - bzip2
    - autoconf
    - automake
    - libtool
    - bison
    - curl
  become: yes
